<Workspace Version="1.3.4.6666" X="-70.2571005122919" Y="169.079414305307" zoom="0.752278291023545" ScaleFactor="1" Name="3DView Lock or Unlock" Description="Use a boolean True to unlock the 3D view. &#xD;&#xA;False locks the 3D view and saves its orientation.&#xD;&#xA;(The default 3D view aka {3D} must be renamed to be saved)" ID="415d88d6-d308-454c-aaa2-11e09cf86f08" Category="GeniusLoci.View">
  <NamespaceResolutionMap>
    <ClassMap partialName="Boolean" resolvedName="Orchid.Revit.Elements.Boolean" assemblyName="OrchidRevit.dll" />
    <ClassMap partialName="Revit.Elements.Views.View3D" resolvedName="Revit.Elements.Views.View3D" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Revit.Application.Document.Current" resolvedName="Revit.Application.Document" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Revit.Application.Document" resolvedName="Revit.Application.Document" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="ea77f9c2-6942-4164-a610-f7048498499e" type="PythonNodeModels.PythonNode" nickname="3Dview Lock or Unlock" x="594.179395821288" y="261.890155147665" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Alban de Chasteigner 2018
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitAPI")
import Autodesk

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

def ProcessList(_func, _list):
    return map( lambda x: ProcessList(_func, x) if type(x)==list else _func(x), _list )

def Unwrap(item):
    return UnwrapElement(item)

if isinstance(IN[0], list):
    views = ProcessList(Unwrap, IN[0])
else:
    views = [Unwrap(IN[0])]

toggle = IN[1]

TransactionManager.Instance.EnsureInTransaction(doc)
for view in views:
	if toggle == True:
		view.Unlock()
	else:
		view.SaveOrientationAndLock()
TransactionManager.Instance.TransactionTaskDone()

if isinstance(IN[0], list): OUT = views 
else: OUT = views[0]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="24c205c0-068c-4ccb-9330-7e31c8551d95" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-286.987612077844" y="178.915601293579" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="ThreeDView: Revit.Elements.Views.View3D = Revit.Application.Document.Current.ActiveView" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="8ca80e2e-64ee-4400-8325-bcefe6bcbf05" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="285.6" y="318" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//True = Unlock&#xD;&#xA;//False = Lock&#xD;&#xA;Toggle : bool=true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="e3626a16-1e9a-40e6-a623-ce199d194a26" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="800.4" y="270" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="ThreeDView" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="ea77f9c2-6942-4164-a610-f7048498499e" start_index="0" end="e3626a16-1e9a-40e6-a623-ce199d194a26" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="24c205c0-068c-4ccb-9330-7e31c8551d95" start_index="0" end="ea77f9c2-6942-4164-a610-f7048498499e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8ca80e2e-64ee-4400-8325-bcefe6bcbf05" start_index="0" end="ea77f9c2-6942-4164-a610-f7048498499e" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>