<Workspace Version="1.3.4.6666" X="192.249524988604" Y="140.826612579436" zoom="0.463139812776717" ScaleFactor="1" Name="All Elements of Types in Document" Description="Collect all elements of a type in a given document." ID="06e467e9-0862-4c07-988a-5bb097f8d1fa" Category="GeniusLoci.Select">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="cfc26829-2536-4704-a4d3-3e7cebf6be8d" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="564.547363335353" y="377.087927037663" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];&#xA;x[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="28c037ad-1d83-488a-988f-03c22ba1a91a" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="755.747363335353" y="339.661260370997" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Element" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="5a2c6408-0ce8-4f04-b6af-b2badd0edce4" type="PythonNodeModels.PythonNode" nickname="Element Types In Document" x="278.947363335353" y="372.87459370433" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager

elementType = IN[0]
inputdocs = UnwrapElement(IN[1]) if isinstance(IN[1],list) else [UnwrapElement(IN[1])]

#Part of script from Clockwork
for inputdoc in inputdocs :
	if inputdoc == None:
		doc = DocumentManager.Instance.CurrentDBDocument
	elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.Document":
		doc = inputdoc
	elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.RevitLinkInstance":
		doc = inputdoc.GetLinkDocument()
	else: doc = None

elements = FilteredElementCollector(doc).OfClass(elementType).ToElements()

OUT = elements, doc</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="0f3315a7-ea61-40b5-b4fb-d1e182ae242e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-238.652636664647" y="343.87459370433" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="elementType" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="e86e692f-aa10-4224-8cab-8087c620e1cf" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-238.652636664647" y="427.87459370433" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// Use only if you want to query a linked model&#xD;&#xA;docOrRevitLinkInstance : var = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="47f87959-b237-4b58-b5ac-eecbae486ff5" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="755.747363335353" y="423.661260370997" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Document" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="cfc26829-2536-4704-a4d3-3e7cebf6be8d" start_index="0" end="28c037ad-1d83-488a-988f-03c22ba1a91a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cfc26829-2536-4704-a4d3-3e7cebf6be8d" start_index="1" end="47f87959-b237-4b58-b5ac-eecbae486ff5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5a2c6408-0ce8-4f04-b6af-b2badd0edce4" start_index="0" end="cfc26829-2536-4704-a4d3-3e7cebf6be8d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0f3315a7-ea61-40b5-b4fb-d1e182ae242e" start_index="0" end="5a2c6408-0ce8-4f04-b6af-b2badd0edce4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e86e692f-aa10-4224-8cab-8087c620e1cf" start_index="0" end="5a2c6408-0ce8-4f04-b6af-b2badd0edce4" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>