<Workspace Version="1.3.4.6666" X="-127.773986402654" Y="77.9296910276537" zoom="0.784369328044827" ScaleFactor="1" Name="Annotation BoundingBox" Description="Get the BoundingBox of the view specific element. (Text, tag, etc)" ID="3a65be19-028d-4a79-9182-1b773b5887d2" Category="GeniusLoci.Geometry">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="ea62f5d5-131c-424d-8f99-651b51bfb96b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="656.675677721371" y="284.477202679528" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Based on a kennyb6's script
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
clr.AddReference('RevitNodes')
import Revit
# Import DocumentManager
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument
clr.ImportExtensions(Revit.GeometryConversion)

annotations=UnwrapElement(IN[0])
if not hasattr(annotations, '__iter__'):
    annotations = [annotations]

bbox = []

for anno in annotations:
    viewId = anno.OwnerViewId
    view = doc.GetElement(viewId)
    bbox.append(anno.BoundingBox[view].ToProtoType())

if isinstance(IN[0], list): OUT = bbox
else: OUT = bbox[0]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="732b5284-7d17-4750-aedf-6efd730f7882" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="552.4" y="287.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="4c577852-16b1-48f0-aa05-813159b45c14" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="827.6" y="281.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="BoundingBox" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="ea62f5d5-131c-424d-8f99-651b51bfb96b" start_index="0" end="4c577852-16b1-48f0-aa05-813159b45c14" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="732b5284-7d17-4750-aedf-6efd730f7882" start_index="0" end="ea62f5d5-131c-424d-8f99-651b51bfb96b" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>