<Workspace Version="1.3.4.6666" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Borrow Element" Description="Obtains ownership for the current user of as many specified elements as possible. " ID="a8d78897-27f6-4702-ba5c-2bb97a5c050d" Category="GeniusLoci.Element">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="6f9e64d0-9737-43bd-b281-6c98971aa435" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="294" y="220.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="86cea918-1f21-4822-afea-f7ae8a7c3dda" type="PythonNodeModels.PythonNode" nickname="Python Script" x="482.4" y="220.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#By Ewan_Opie
import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference('System')
from System.Collections.Generic import List

elements = UnwrapElement(IN[0]) if isinstance(IN[0],list) else [UnwrapElement(IN[0])]
checkedout_elem=[]

ids = [elem.Id for elem in elements]
IDS = List[ElementId](ids)

try: checkedout_elem = [doc.GetElement(checkedout_el) for checkedout_el in WorksharingUtils.CheckoutElements(doc,IDS)]
	checkedout_elem = List[Element](checkedout_elem)
except Exception,er: checkedout_elem.append(str(er))

OUT = checkedout_elem</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="9ff9e3cb-74a7-4d1e-90d1-bf8acb2b1220" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="706.8" y="220.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Element" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="6f9e64d0-9737-43bd-b281-6c98971aa435" start_index="0" end="86cea918-1f21-4822-afea-f7ae8a7c3dda" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="86cea918-1f21-4822-afea-f7ae8a7c3dda" start_index="0" end="9ff9e3cb-74a7-4d1e-90d1-bf8acb2b1220" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>