<Workspace Version="1.3.4.6666" X="-437.187634877047" Y="220.391386568235" zoom="0.813145682173101" ScaleFactor="1" Name="Compound Edges References" Description="Get the vertical edges and their references of the roof, floor, ceiling or wall.&#xD;&#xA;Also works with linked element." ID="4038d8dc-94dc-4f32-844c-f2d1ba52e668" Category="GeniusLoci.Reference">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="c1623bbf-dc2a-4919-bd3d-e6774cbf8918" type="PythonNodeModels.PythonNode" nickname="Python Script" x="751.497713051438" y="38.3812938903836" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Alban de Chasteigner 2019
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com

import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)
from Revit.Elements import *

items = UnwrapElement(IN[0]) if isinstance(IN[0],list) else [UnwrapElement(IN[0])]

def split_half(a):
	half = len(a) &gt;&gt; 1
	#return a[:half], a[half:]
	return a[half:]

allHorizEdges,allVertEdges,allVertReferences=[],[],[]

opt = Options()
opt.ComputeReferences = True
#opt.IncludeNonVisibleObjects = True
#opt.View = doc.ActiveView
for item in items:
	for obj in item.get_Geometry(opt):
		if isinstance(obj, Solid):
			gline = obj
			vertEdges,horizEdges,vertReferences=[],[],[]
			for edges in gline.Edges:
				if round(edges.AsCurve().GetEndPoint(0).ToPoint().Z,10) != round(edges.AsCurve().GetEndPoint(1).ToPoint().Z,10):
					vertEdges.append(edges.AsCurve().ToProtoType())
					vertReferences.append(edges.Reference)
				else:
					horizEdges.append(edges.AsCurve().ToProtoType())
			if isinstance(item, Autodesk.Revit.DB.Wall):
				allHorizEdges.append(horizEdges)
			else:
				allHorizEdges.append(split_half(horizEdges))
			allVertEdges.append(vertEdges)
			allVertReferences.append(vertReferences)
		
if isinstance(IN[0], list): OUT = allHorizEdges,allVertEdges,allVertReferences
else: OUT = allHorizEdges[0],allVertEdges[0],allVertReferences[0]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="83d6a35d-c831-4732-a6f7-6afd66a625e4" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="441.512708936443" y="37.1255428684909" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Roof, floor, ceiling or wall&#xD;&#xA;element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="e8d6ce98-15d6-4908-8cde-2f424a334780" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1017.77634661742" y="41.5554533298155" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Horizontal Edges" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="79cc1390-d693-4853-b962-b3cd887eaadc" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1024.0547083898" y="106.352912899912" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Vertical Edges" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="715b1388-a4fc-4fbe-85a0-7bdaf5c8a38c" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="912.627244362361" y="38.8372755637639" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];&#xA;x[1];&#xA;x[2];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="3f76c3ca-274a-444c-a7eb-48083b176186" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1011.07145143335" y="186.301009819684" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Vertical References" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="c1623bbf-dc2a-4919-bd3d-e6774cbf8918" start_index="0" end="715b1388-a4fc-4fbe-85a0-7bdaf5c8a38c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="83d6a35d-c831-4732-a6f7-6afd66a625e4" start_index="0" end="c1623bbf-dc2a-4919-bd3d-e6774cbf8918" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="715b1388-a4fc-4fbe-85a0-7bdaf5c8a38c" start_index="0" end="e8d6ce98-15d6-4908-8cde-2f424a334780" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="715b1388-a4fc-4fbe-85a0-7bdaf5c8a38c" start_index="1" end="79cc1390-d693-4853-b962-b3cd887eaadc" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="715b1388-a4fc-4fbe-85a0-7bdaf5c8a38c" start_index="2" end="3f76c3ca-274a-444c-a7eb-48083b176186" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>