<Workspace Version="1.3.4.6666" X="142.141127168217" Y="196.052384310401" zoom="0.487258594699403" ScaleFactor="1" Name="Convert from SurveyPoint CoordinateSystem" Description="Convert from Survey Coordinate to Internal Origin Coordinate." ID="10f202e9-2198-43dc-8632-242ca8b2c7d6" Category="GeniusLoci.Geometry">
  <NamespaceResolutionMap>
    <ClassMap partialName="CoordinateSystem" resolvedName="Autodesk.DesignScript.Geometry.CoordinateSystem" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Coordinates" resolvedName="Revit.Elements.Coordinates" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry" resolvedName="Autodesk.DesignScript.Geometry.Geometry" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Geometry" resolvedName="Autodesk.DesignScript.Geometry.Geometry" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c3899592-6430-4ef5-be9d-840eaf908844" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-74.7405453872209" y="273.676885801779" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Point in Survey Coordinate System&#xD;&#xA;point: Autodesk.DesignScript.Geometry.Point[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="c3080e04-615e-475a-9b88-1c5fac9ef6d4" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="684.459454612779" y="273.676885801779" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="//Point in Internal Origin Coordinate System&#xD;&#xA;Point" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="87e02216-b504-4dcd-858b-bd672b7a94ef" type="PythonNodeModels.PythonNode" nickname="Python Script" x="460.059454612779" y="273.676885801779" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

pts = [pt.ToXyz(True) for pt in IN[0]] if isinstance(IN[0],list) else [IN[0].ToXyz(True)]

#Translate point from Shared coordinates to Internal
translatedPoint = [doc.ActiveProjectLocation.GetTotalTransform().OfPoint(pt).ToPoint() for pt in pts]

if isinstance(IN[0], list): OUT = translatedPoint
else: OUT = translatedPoint[0]</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="c3899592-6430-4ef5-be9d-840eaf908844" start_index="0" end="87e02216-b504-4dcd-858b-bd672b7a94ef" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="87e02216-b504-4dcd-858b-bd672b7a94ef" start_index="0" end="c3080e04-615e-475a-9b88-1c5fac9ef6d4" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>