<Workspace Version="1.3.4.6666" X="58.587165" Y="23.574915" zoom="0.70823125" ScaleFactor="1" Name="Convert Linked Reference" Description="Creates a usable reference from a reference from a linked document." ID="5c770bc5-de60-41c7-a2cd-2bccd79a6a89" Category="GeniusLoci.Reference">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="0b6fa884-7673-4532-9967-07375f59aeea" type="PythonNodeModels.PythonNode" nickname="Python Script" x="277.2" y="251.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Based on a C# script by Fair59
#https://forums.autodesk.com/t5/revit-api-forum/create-dimensions-for-familyinstance-in-linked-file/td-p/8424237
import clr
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

linkReferences = IN[0] if isinstance(IN[0],list) else [IN[0]]
linkedInstance = UnwrapElement(IN[1])

def parseLinkedReference(doc, linkedRef):
	reps = linkedRef.ConvertToStableRepresentation(doc).split(':')      
	res = ''
	first=True        
	for i, s in enumerate(reps):
		t = s
		if "RVTLINK" in s:
			if(i&lt;len(reps)-1):
				if reps[i+1]=="0":
					t = "RVTLINK"
				else:
					t = "0:RVTLINK"
			else:
				t = "0:RVTLINK"
		if not first:
			res = res + ":" + t
		else:
			res = t
			first = False          
	ref = Reference.ParseFromStableRepresentation(doc,res)
	return ref

refArray = ReferenceArray()
for refLink in linkReferences:
	linkedReference = refLink.CreateLinkReference(linkedInstance)
	ref = parseLinkedReference(doc,linkedReference)
	refArray.Append(ref)

OUT = refArray</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="ab3cbefb-269b-4118-8224-100902bece8c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="112.157868634009" y="222.681701774668" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Reference" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="f0e34b91-6ba7-425f-a7ab-8792fad03d6e" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="443.6" y="252" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Reference" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="6f043d7b-da8b-4439-8c6e-d613f800c60e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="51.7961714116987" y="302.854081522273" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="RevitLinkInstance" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="0b6fa884-7673-4532-9967-07375f59aeea" start_index="0" end="f0e34b91-6ba7-425f-a7ab-8792fad03d6e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ab3cbefb-269b-4118-8224-100902bece8c" start_index="0" end="0b6fa884-7673-4532-9967-07375f59aeea" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6f043d7b-da8b-4439-8c6e-d613f800c60e" start_index="0" end="0b6fa884-7673-4532-9967-07375f59aeea" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>