<Workspace Version="1.3.4.6666" X="-42.5002553815701" Y="-128.411670218027" zoom="0.635856709296407" ScaleFactor="1" Name="Create Independent Tag" Description="Works only in Revit 2018 and later.&#xD;&#xA;This node will create a tag at a given location, of given type and in a supplied view. &#xD;&#xA;The node also works with Linked Elements (except space and area), Multi Category tag and Material Tag.&#xD;&#xA;Based on an archilab node" ID="ee3e4c3a-599a-4dba-af1f-57f58b08ce3d" Category="GeniusLoci.Tag">
  <NamespaceResolutionMap>
    <ClassMap partialName="Revit.Application.Document.Current" resolvedName="Revit.Application.Document" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Revit.Application.Document" resolvedName="Revit.Application.Document" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="70e4b9db-16ca-409a-a82e-5e420fcbec2b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="590.115172706277" y="554.012701372108" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="8">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <PortInfo index="4" default="False" />
      <PortInfo index="5" default="False" />
      <PortInfo index="6" default="False" />
      <PortInfo index="7" default="False" />
      <Script>#Copyright(c) 2015, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net
#This node is an update to Create Annotation Tag node that can be found in archi-lab package. Thanks to Konrad K Sobon for making the original one.
# Ability to tag Linked elements by Alban de Chasteigner

import clr
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)

import sys
sys.path.append(r"C:\Program Files (x86)\IronPython 2.7\Lib")

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

views = UnwrapElement(IN[0])
elements = UnwrapElement(IN[1]) if isinstance(IN[1],list) else [UnwrapElement(IN[1])]
locationPts = UnwrapElement(IN[2]) if isinstance(IN[2],list) else [UnwrapElement(IN[2])]
tagType = UnwrapElement(IN[3])

tagOrientation = IN[4]
if tagOrientation == True :
	tagOrientation = TagOrientation.Horizontal
	spTagOrientation = SpatialElementTagOrientation.Horizontal
elif tagOrientation == False :
	tagOrientation = TagOrientation.Vertical
	spTagOrientation = SpatialElementTagOrientation.Vertical

leader = IN[5]

if IN[6] != None:
	link = UnwrapElement(IN[6])
else:
	link = None
	
RunIt = IN[7]

#ueWrapper from Dimitar Venkov
ueWrapper = None
wrappers = clr.GetClrType(Revit.Elements.ElementWrapper).GetMethods()
for w in wrappers:
	if w.ToString().startswith("Revit.Elements.UnknownElement"):
		ueWrapper = w
		break
				
def toRvtPoint(point):
	return point.ToXyz()

def toRvtId(_id):
	if isinstance(_id, int) or isinstance(_id, str):
		id = ElementId(int(_id))
		return id
	elif isinstance(_id, ElementId):
		return _id

tagTypeId = toRvtId(tagType.Id)
chk = []
try:
	errorReport = None
	if RunIt:
		if tagType.Category.Id == ElementId(BuiltInCategory.OST_RoomTags):
			roomTags = []
			if isinstance(IN[0], list):
				for j in views:
					for i,k in zip(elements, locationPts):
						TransactionManager.Instance.EnsureInTransaction(doc)
						#added the if statement to get roomId from the linked element.
						if link != None:
							roomId = LinkElementId(link.Id, i.Id)
						else:
							roomId = LinkElementId(i.Id)
						location = Autodesk.Revit.DB.UV(toRvtPoint(k).X, toRvtPoint(k).Y)
						roomTag = doc.Create.NewRoomTag(roomId, location, j.Id)
						roomTag.RoomTagType = tagType
						roomTag.TagOrientation = spTagOrientation
						roomTag.HasLeader = leader
						chk.append(roomId)
						roomTags.append(roomTag)
						TransactionManager.Instance.TransactionTaskDone()
			else:
				TransactionManager.Instance.EnsureInTransaction(doc)
				for i, j in zip(elements, locationPts):
					if link != None:
						roomId = LinkElementId(link.Id, i.Id)
					else:
						roomId = LinkElementId(i.Id)
					location = Autodesk.Revit.DB.UV(toRvtPoint(j).X, toRvtPoint(j).Y)
					roomTag = doc.Create.NewRoomTag(roomId, location, views.Id)
					roomTag.RoomTagType = tagType
					roomTag.TagOrientation = spTagOrientation
					roomTag.HasLeader = leader
					roomTags.append(roomTag)
				TransactionManager.Instance.TransactionTaskDone()
			result = roomTags
		elif tagType.Category.Id == ElementId(BuiltInCategory.OST_MEPSpaceTags):
			TransactionManager.Instance.EnsureInTransaction(doc)
			roomTags = []
			if isinstance(IN[0], list):
				for j in views:
					for i,k in zip(elements, locationPts):
						location = Autodesk.Revit.DB.UV(toRvtPoint(k).X, toRvtPoint(k).Y)
						spaceTag = doc.Create.NewSpaceTag(i, location, j)
						spaceTag.SpaceTagType = tagType
						spaceTag.TagOrientation = spTagOrientation
						spaceTag.HasLeader = leader
						roomTags.append(spaceTag)
			else:
				for i, j in zip(elements, locationPts):
					location = Autodesk.Revit.DB.UV(toRvtPoint(j).X, toRvtPoint(j).Y)
					spaceTag = doc.Create.NewSpaceTag(i,location, views)
					spaceTag.SpaceTagType = tagType
					spaceTag.TagOrientation = spTagOrientation
					spaceTag.HasLeader = leader
					roomTags.append(spaceTag)
			TransactionManager.Instance.TransactionTaskDone()
			result = roomTags
		elif tagType.Category.Id == ElementId(BuiltInCategory.OST_AreaTags):
			TransactionManager.Instance.EnsureInTransaction(doc)
			roomTags = []
			if isinstance(IN[0], list):
				for j in views:
					for i,k in zip(elements, locationPts):
						location = Autodesk.Revit.DB.UV(toRvtPoint(k).X, toRvtPoint(k).Y)
						areaTag = doc.Create.NewAreaTag(j,i, location)
						areaTag.AreaTagType = tagType
						areaTag.TagOrientation = spTagOrientation
						areaTag.HasLeader = leader
						roomTags.append(areaTag)
			else:
				for i, j in zip(elements, locationPts):
					location = Autodesk.Revit.DB.UV(toRvtPoint(j).X, toRvtPoint(j).Y)
					areaTag = doc.Create.NewAreaTag(views,i,location)
					areaTag.AreaTagType = tagType
					areaTag.TagOrientation = spTagOrientation
					areaTag.HasLeader = leader
					roomTags.append(areaTag)
			TransactionManager.Instance.TransactionTaskDone()
			result = roomTags
		elif tagType.Category.Id == ElementId(BuiltInCategory.OST_MultiCategoryTags):
			TransactionManager.Instance.EnsureInTransaction(doc)
			multitags = []
			if isinstance(IN[0], list):
				for j in views:
					for i,k in zip(elements, locationPts):
						if link != None:
							reference = Reference(i).CreateLinkReference(link)
						else:
							reference = Reference(i)
						location = toRvtPoint(k)
						tag = IndependentTag.Create(doc,j.Id, reference, 	leader, TagMode.TM_ADDBY_MULTICATEGORY, 	tagOrientation, location)
						tag.ChangeTypeId(tagTypeId)
						if link == None:
							multitags.append(tag)
						else:
							multitags.append(ueWrapper.Invoke(None,(tag, True)))
			else:
				for i, j in zip(elements, locationPts):
					if link != None:
						reference = Reference(i).CreateLinkReference(link)
					else:
						reference = Reference(i)
					location = toRvtPoint(j)
					tag = IndependentTag.Create(doc, views.Id, reference, leader, TagMode.TM_ADDBY_MULTICATEGORY, tagOrientation, location)
					tag.ChangeTypeId(tagTypeId)
					if link == None:
						multitags.append(tag)
					else:
						multitags.append(ueWrapper.Invoke(None,(tag, True)))
			TransactionManager.Instance.TransactionTaskDone()
			result = multitags
		elif tagType.Category.Id == ElementId(BuiltInCategory.OST_MaterialTags):
			TransactionManager.Instance.EnsureInTransaction(doc)
			Mattags = []
			if isinstance(IN[0], list):
				for j in views:
					for i,k in zip(elements, locationPts):
						if link != None:
							reference = Reference(i).CreateLinkReference(link)
						else:
							reference = Reference(i)
						location = toRvtPoint(k)
						tag = IndependentTag.Create(doc, j.Id, reference, leader, TagMode.TM_ADDBY_MATERIAL, tagOrientation, location)
						tag.ChangeTypeId(tagTypeId)
						if link == None:
							Mattags.append(tag)
						else:
							Mattags.append(ueWrapper.Invoke(None,(tag, True)))
			else:
				for i, j in zip(elements, locationPts):
					if link != None:
						reference = Reference(i).CreateLinkReference(link)
					else:
						reference = Reference(i)
					location = toRvtPoint(j)
					tag = IndependentTag.Create(doc, views.Id, reference, leader, TagMode.TM_ADDBY_MATERIAL, tagOrientation, location)
					tag.ChangeTypeId(tagTypeId)
					if link == None:
						Mattags.append(tag)
					else:
						Mattags.append(ueWrapper.Invoke(None,(tag, True)))
			TransactionManager.Instance.TransactionTaskDone()
			result = Mattags
		else:
			TransactionManager.Instance.EnsureInTransaction(doc)
			tags = []
			if isinstance(IN[0], list):
				for j in views:
					for i,k in zip(elements, locationPts):
						if link != None:
							reference = Reference(i).CreateLinkReference(link)
						else:
							reference = Reference(i)
						location = toRvtPoint(k)
						tag = IndependentTag.Create(doc, j.Id, reference, leader, TagMode.TM_ADDBY_CATEGORY, tagOrientation, location)
						tag.ChangeTypeId(tagTypeId)
						if link == None:
							tags.append(tag)
						else:
							tags.append(ueWrapper.Invoke(None,(tag, True)))
			else:
				for i, j in zip(elements, locationPts):
					if link != None:
						reference = Reference(i).CreateLinkReference(link)
					else:
						reference = Reference(i)
					location = toRvtPoint(j)
					tag = IndependentTag.Create(doc, views.Id, reference, leader, TagMode.TM_ADDBY_CATEGORY, tagOrientation, location)
					tag.ChangeTypeId(tagTypeId)
					if link == None:
						tags.append(tag)
					else:
						tags.append(ueWrapper.Invoke(None,(tag, True)))
			TransactionManager.Instance.TransactionTaskDone()
			result = tags
	else:
		result = "RunIt is set to False."
except:
	# if error accurs anywhere in the process catch it
	import traceback
	errorReport = traceback.format_exc()

#Assign your output to the OUT variable
if errorReport == None:
	OUT = result
else:
	OUT = errorReport</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="5b3b7735-048c-455a-a61b-66739a43594f" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="814.915172706277" y="554.012701372108" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Tag" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="4acb11bf-629f-47e1-8a84-9e5be63f6afe" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-34.6848272937227" y="320.012701372108" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//View to tag in.&#xD;&#xA;view:var[]..[]=Revit.Application.Document.Current.ActiveView" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="7e0dfe11-fc12-4ce5-83e6-a665b5725bde" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-34.6848272937227" y="413.012701372108" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Element to tag&#xD;&#xA;element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="5f4706a4-075e-4d75-9f8b-3eabc6b2e34b" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-34.6848272937227" y="507.012701372108" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Point&#xD;&#xA;TagLocation" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="b31b9440-8b19-4360-a5ea-1ca4fa6ace14" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-34.6848272937227" y="600.012701372108" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Family Type to use&#xD;&#xA;TagType" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="3b7ff1e2-c1fd-4aa0-9eca-1be98d70bee3" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-34.6848272937227" y="693.012701372108" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Optional : Place tag horizontal, defaults to true&#xD;&#xA;horizontal : bool = true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="aed348c3-980f-4057-a4a0-b828a2eb454e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-34.6848272937227" y="786.012701372108" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Optional : Add a leader, defaults to false&#xD;&#xA;addLeader : bool = false" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="9178078f-0743-4413-a8d7-af3fbb45699c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-34.6848272937227" y="879.012701372108" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="LinkInstance:var=null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="b7b05d33-4982-45e7-a34e-24bd7769cb66" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-34.6848272937227" y="962.012701372108" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="RunIt:bool=false" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="70e4b9db-16ca-409a-a82e-5e420fcbec2b" start_index="0" end="5b3b7735-048c-455a-a61b-66739a43594f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4acb11bf-629f-47e1-8a84-9e5be63f6afe" start_index="0" end="70e4b9db-16ca-409a-a82e-5e420fcbec2b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7e0dfe11-fc12-4ce5-83e6-a665b5725bde" start_index="0" end="70e4b9db-16ca-409a-a82e-5e420fcbec2b" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5f4706a4-075e-4d75-9f8b-3eabc6b2e34b" start_index="0" end="70e4b9db-16ca-409a-a82e-5e420fcbec2b" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b31b9440-8b19-4360-a5ea-1ca4fa6ace14" start_index="0" end="70e4b9db-16ca-409a-a82e-5e420fcbec2b" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3b7ff1e2-c1fd-4aa0-9eca-1be98d70bee3" start_index="0" end="70e4b9db-16ca-409a-a82e-5e420fcbec2b" end_index="4" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="aed348c3-980f-4057-a4a0-b828a2eb454e" start_index="0" end="70e4b9db-16ca-409a-a82e-5e420fcbec2b" end_index="5" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9178078f-0743-4413-a8d7-af3fbb45699c" start_index="0" end="70e4b9db-16ca-409a-a82e-5e420fcbec2b" end_index="6" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b7b05d33-4982-45e7-a34e-24bd7769cb66" start_index="0" end="70e4b9db-16ca-409a-a82e-5e420fcbec2b" end_index="7" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>