<Workspace Version="1.3.4.6666" X="0" Y="0" zoom="1" ScaleFactor="1" Name="CurtainWall Vertical References" Description="Collects references from the vertical grid lines of the curtain wall. Also works with a linked curtain wall." ID="4aa1ec1c-8bc8-4a81-ab5c-c1bcd3a04c06" Category="GeniusLoci.Reference">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="38c76dbc-3c60-4acd-bb09-8d6ffa90cb19" type="PythonNodeModels.PythonNode" nickname="Python Script" x="325.2" y="299.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Based on a script of maciek.glowka : http://lubim.co
import clr
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

walls = UnwrapElement(IN[0])
if not hasattr(walls, '__iter__'):
    walls = [walls]

def isParallel(v1,v2):
	return v1.CrossProduct(v2).IsAlmostEqualTo(XYZ(0,0,0))
	
for wall in walls:
	line = wall.Location.Curve
	lineDir = line.GetEndPoint(1) - line.GetEndPoint(0)
	doc=wall.Document
	
refArray = ReferenceArray()
options = Options()
options.ComputeReferences = True
options.IncludeNonVisibleObjects = True
geoElement = wall.get_Geometry(options)
#get side references
for obj in geoElement:
	if isinstance(obj,Solid):
		for f in obj.Faces:
			faceNormal = f.FaceNormal
			if isParallel(faceNormal,lineDir):
				refArray.Append(f.Reference)
    
#get grid references
for id in wall.CurtainGrid.GetVGridLineIds():
	gridLine = doc.GetElement(id)
	gridGeo = gridLine.get_Geometry(options)
	for obj in gridGeo:
		if isinstance(obj,Line):
			refArray.Append(obj.Reference)

OUT = refArray</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="1e77bd95-187a-4c75-9795-d3524dfe5b10" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="65.9999999999999" y="302.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="CurtainWall: var[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="abf10036-7def-4cd1-be75-b3859b1ceba3" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="472.4" y="299.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="References" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="38c76dbc-3c60-4acd-bb09-8d6ffa90cb19" start_index="0" end="abf10036-7def-4cd1-be75-b3859b1ceba3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1e77bd95-187a-4c75-9795-d3524dfe5b10" start_index="0" end="38c76dbc-3c60-4acd-bb09-8d6ffa90cb19" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>