<Workspace Version="1.3.4.6666" X="-365.6" Y="-20.4" zoom="1" ScaleFactor="1" Name="Element Filter By Name Contains" Description="Filter elements by part of their name." ID="6c252e3f-9c04-4660-85cb-117472080ad6" Category="GeniusLoci.Element">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="03b85170-5126-4526-b484-0f017fe6be37" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="403" y="248" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Element to filter by name contains&#xD;&#xA;element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="f2e4a140-a84f-40b4-8088-d418e8f210aa" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="435" y="369" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//The string value to filter by&#xD;&#xA;searchString : string[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="615a0f01-e49c-4f8c-8599-30da85baec3a" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="483.4" y="500" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="ignoreCase:bool=false" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="65dde85c-cc9b-4eb0-bd21-e01a3366b3e8" type="PythonNodeModels.PythonNode" nickname="Python Script" x="859.2" y="308.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>#Alban de Chasteigner 2020
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com

import clr
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import Element
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

elements = UnwrapElement(IN[0]) if isinstance(IN[0],list) else [UnwrapElement(IN[0])]
names = IN[1] if isinstance(IN[1],list) else [IN[1]]
bool = IN[2]
outList=[]

for elem in elements:
	if isinstance(IN[1],list):
		if bool:
			if any(name.lower() in elem.ToDSType(True).Name.lower() for name in names):
				outList.append(elem)
		else:
			if any(name in elem.ToDSType(True).Name for name in names):
				outList.append(elem)
	else:
		if bool:
			outList=[elem for elem in elements if IN[1].lower() in elem.ToDSType(True).Name.lower()]
		else:
			outList=[elem for elem in elements if IN[1] in elem.ToDSType(True).Name]
	
if isinstance(IN[0], list): OUT = outList
else: OUT = outList[0]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="aea164f2-7019-4307-b297-0ae76a1e934a" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1085.2" y="312" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Element" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="03b85170-5126-4526-b484-0f017fe6be37" start_index="0" end="65dde85c-cc9b-4eb0-bd21-e01a3366b3e8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f2e4a140-a84f-40b4-8088-d418e8f210aa" start_index="0" end="65dde85c-cc9b-4eb0-bd21-e01a3366b3e8" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="615a0f01-e49c-4f8c-8599-30da85baec3a" start_index="0" end="65dde85c-cc9b-4eb0-bd21-e01a3366b3e8" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="65dde85c-cc9b-4eb0-bd21-e01a3366b3e8" start_index="0" end="aea164f2-7019-4307-b297-0ae76a1e934a" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>