<Workspace Version="1.3.4.6666" X="-51.1876650765887" Y="-137.120720145194" zoom="0.867977507649015" ScaleFactor="1" Name="FamilyInstance Reference ByType" Description="Works only in Revit 2018.1 and later.&#xD;&#xA;Gets the reference corresponding to the given Reference Plane in the family instance.&#xD;&#xA;Also works with linked family instance." ID="27053731-def9-46b7-8a8f-d05ef3a8e51f" Category="GeniusLoci.Reference">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="38be3203-5e10-47a6-af50-d8935cb365f0" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="893.345177085362" y="371.190190955317" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Reference" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="f5b3a585-0eb1-44e9-8bd8-c2d7a8cc5451" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="90.9451770853621" y="407.616857621984" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="familyInstance" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="1d7f7507-7038-4532-a0c4-24d8cac0d2af" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="90.9451770853621" y="491.616857621984" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Default = Center (Left/Right)&#xD;&#xA;ReferenceType:var=null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="7d764139-a2fc-47d9-bf62-d29c5e6629ae" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="702.145177085362" y="440.830190955317" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];&#xA;x[1];&#xA;x[2];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="2351f917-5f81-4c8e-a937-6f262e53e7b8" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="893.345177085362" y="454.190190955317" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="ReferenceName" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="797a7ebc-708b-4012-b1b0-7f4b5ac20679" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="893.345177085362" y="537.190190955317" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Plane" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="4d340dd1-eee3-4aab-a759-d4743361f4c8" type="PythonNodeModels.PythonNode" nickname="Python Script" x="477.345177085362" y="436.616857621984" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Alban de Chasteigner 2018
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com

import clr
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

elements = UnwrapElement(IN[0]) if isinstance(IN[0],list) else [UnwrapElement(IN[0])]
reftype = UnwrapElement(IN[1])
ref,refname,planeList=[],[],[]

#Get Reference Planes from Families
for element in elements:
	if reftype == None:
		reference = element.GetReferences(FamilyInstanceReferenceType.CenterLeftRight)
	else :
		reference = element.GetReferences(reftype)
	ref.append(reference[0])
	refname.append(element.GetReferenceName(reference[0]))
	try :
		TransactionManager.Instance.EnsureInTransaction(doc)
		trans1 = SubTransaction(doc)
		trans1.Start()
		sketch=SketchPlane.Create(doc,reference[0])
		plane = sketch.GetPlane().ToPlane(True)
		sketch.Dispose()
		trans1.RollBack()
		TransactionManager.Instance.TransactionTaskDone()
	except :
		plane=None
	planeList.append(plane)

if isinstance(IN[0], list): OUT = ref,refname,planeList
else: OUT = ref[0],refname[0],planeList[0]</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="f5b3a585-0eb1-44e9-8bd8-c2d7a8cc5451" start_index="0" end="4d340dd1-eee3-4aab-a759-d4743361f4c8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1d7f7507-7038-4532-a0c4-24d8cac0d2af" start_index="0" end="4d340dd1-eee3-4aab-a759-d4743361f4c8" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7d764139-a2fc-47d9-bf62-d29c5e6629ae" start_index="0" end="38be3203-5e10-47a6-af50-d8935cb365f0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7d764139-a2fc-47d9-bf62-d29c5e6629ae" start_index="1" end="2351f917-5f81-4c8e-a937-6f262e53e7b8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7d764139-a2fc-47d9-bf62-d29c5e6629ae" start_index="2" end="797a7ebc-708b-4012-b1b0-7f4b5ac20679" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4d340dd1-eee3-4aab-a759-d4743361f4c8" start_index="0" end="7d764139-a2fc-47d9-bf62-d29c5e6629ae" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>