<Workspace Version="1.3.4.6666" X="-90.8717641402426" Y="-1.36754264941848" zoom="0.784369328044827" ScaleFactor="1" Name="FamilyInstance Reference ByRefPlane" Description="Works only in Revit 2018.1 and later.&#xD;&#xA;Gets family instance references corresponding to the reference planes in the instance's family. " ID="27053731-def9-46b7-8a8f-d05ef3a8e51f" Category="GeniusLoci.Reference">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="38be3203-5e10-47a6-af50-d8935cb365f0" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="906.4" y="262.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Reference" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="f5b3a585-0eb1-44e9-8bd8-c2d7a8cc5451" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="104" y="298.826666666667" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="familyInstance" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="1d7f7507-7038-4532-a0c4-24d8cac0d2af" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="104" y="382.826666666667" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Default = Center (Left/Right)&#xD;&#xA;ReferenceType=null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="7d764139-a2fc-47d9-bf62-d29c5e6629ae" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="715.2" y="332.04" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];&#xA;x[1];&#xA;x[2];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="2351f917-5f81-4c8e-a937-6f262e53e7b8" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="906.4" y="345.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="ReferenceName" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="797a7ebc-708b-4012-b1b0-7f4b5ac20679" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="906.4" y="428.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="SketchPlane" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="4d340dd1-eee3-4aab-a759-d4743361f4c8" type="PythonNodeModels.PythonNode" nickname="Python Script" x="490.4" y="327.826666666667" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

elements = UnwrapElement(IN[0]) if isinstance(IN[0],list) else [UnwrapElement(IN[0])]
reftype = UnwrapElement(IN[1])
ref,refname,sketch=[],[],[]

TransactionManager.Instance.EnsureInTransaction(doc)
#Get Reference Planes from Families
for element in elements:
	if reftype == None:
		reference = element.GetReferences(FamilyInstanceReferenceType.CenterLeftRight)
	else :
		reference = element.GetReferences(reftype)
	ref.append(reference[0])
	refname.append(element.GetReferenceName(reference[0]))
	try :
		sketch.append(SketchPlane.Create(doc,reference[0]))
	except :
		sketch.append(None)
TransactionManager.Instance.TransactionTaskDone()

if isinstance(IN[0], list): OUT = ref,refname,sketch
else: OUT = ref[0],refname[0],sketch[0]</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="f5b3a585-0eb1-44e9-8bd8-c2d7a8cc5451" start_index="0" end="4d340dd1-eee3-4aab-a759-d4743361f4c8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1d7f7507-7038-4532-a0c4-24d8cac0d2af" start_index="0" end="4d340dd1-eee3-4aab-a759-d4743361f4c8" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7d764139-a2fc-47d9-bf62-d29c5e6629ae" start_index="0" end="38be3203-5e10-47a6-af50-d8935cb365f0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7d764139-a2fc-47d9-bf62-d29c5e6629ae" start_index="1" end="2351f917-5f81-4c8e-a937-6f262e53e7b8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7d764139-a2fc-47d9-bf62-d29c5e6629ae" start_index="2" end="797a7ebc-708b-4012-b1b0-7f4b5ac20679" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4d340dd1-eee3-4aab-a759-d4743361f4c8" start_index="0" end="7d764139-a2fc-47d9-bf62-d29c5e6629ae" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>