<Workspace Version="1.3.4.6666" X="102.926" Y="13.8220000000001" zoom="0.8425" ScaleFactor="1" Name="Get Elements at Ends" Description="Get the two elements joining to the ends." ID="664d8bd8-fdef-4716-95cd-8105c2fd897b" Category="GeniusLoci.Element">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="ff682464-b97a-492a-9253-218a69c6ebd7" type="PythonNodeModels.PythonNode" nickname="Python Script" x="384.011089434403" y="456.169997261763" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Alban de Chasteigner 2019
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)
from Revit.Elements import *

from itertools import chain

items = UnwrapElement(IN[0])
if not hasattr(items, '__iter__'):
	items = [items]
	
join,result = [],[]

for item in items:
	loc = item.Location
	for ip in range(0, 2):
		join.append(loc.ElementsAtJoin[ip])
		flatlist = list(chain.from_iterable(join))
	for wall in flatlist :
		if wall.Id != item.Id :
			result.append(wall)

OUT = result</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="4ddcdcbe-3567-44f2-a276-05a48af61676" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="10.7999999999999" y="450" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Curve based element&#xD;&#xA;//Longest lacing for several elements&#xD;&#xA;element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="64d43d8e-c939-4167-9b51-75db23c61aca" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="547.6" y="450" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="ff682464-b97a-492a-9253-218a69c6ebd7" start_index="0" end="64d43d8e-c939-4167-9b51-75db23c61aca" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4ddcdcbe-3567-44f2-a276-05a48af61676" start_index="0" end="ff682464-b97a-492a-9253-218a69c6ebd7" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>