<Workspace Version="1.3.4.6666" X="-152.017132402985" Y="25.1636055484788" zoom="0.616107147327431" ScaleFactor="1" Name="Group Lines by Orthogonality" Description="Group vertical, horizontal and oblique lines together. Works with dynamo lines et MEPCurves elements (duct, pipe, cable tray and conduit)." ID="e3e4a945-0317-41d4-be74-2be515991830" Category="GeniusLoci.Geometry">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="bfc18d55-a652-42c0-85fb-b640e2646b10" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="261.245865585547" y="304.319114420448" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Dynamo line or MEPCurves (Duct, pipe...)&#xD;&#xA;lines" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="3316e090-050c-48b3-a035-110d36ec8c5d" type="PythonNodeModels.PythonNode" nickname="Filter Lines" x="683.3" y="305.526666666667" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Alban de Chasteigner 2020
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com

import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

elements = UnwrapElement(IN[0]) if isinstance(IN[0],list) else [UnwrapElement(IN[0])]
	
horizontal,vertical, slope =[],[],[]

for element in elements:
	if hasattr(element, "Explode"):
		curve=element.ToRevitType()
	elif hasattr(element, "Location") and isinstance(element.Location, Autodesk.Revit.DB.LocationCurve):
		curve=element.Location.Curve
	if round(curve.GetEndPoint(0).Z,2) == round(curve.GetEndPoint(1).Z,2):
		horizontal.append(element)
	elif round(curve.GetEndPoint(0).X,2) == round(curve.GetEndPoint(1).X,2) and round(curve.GetEndPoint(0).Y,2) == round(curve.GetEndPoint(1).Y,2):
		vertical.append(element)
	else: slope.append(element)
	
if isinstance(IN[0], (list)): OUT = vertical,horizontal,slope
else: OUT = vertical[0],horizontal[0],slope[0]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="f055dde1-6357-4964-9004-9e36d3494ef3" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="907.7" y="309.74" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];&#xA;x[1];&#xA;x[2];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="84dad3de-5789-449d-91b5-dc1537e962db" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1098.9" y="240.1" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Vertical" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="b7952ae2-e4b7-4a5d-900d-1eddef18a1c4" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1098.9" y="323.1" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Horizontal" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="ff14cc85-5c93-40cb-9746-34f5133284e0" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1098.9" y="406.1" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Sloping" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="bfc18d55-a652-42c0-85fb-b640e2646b10" start_index="0" end="3316e090-050c-48b3-a035-110d36ec8c5d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3316e090-050c-48b3-a035-110d36ec8c5d" start_index="0" end="f055dde1-6357-4964-9004-9e36d3494ef3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f055dde1-6357-4964-9004-9e36d3494ef3" start_index="0" end="84dad3de-5789-449d-91b5-dc1537e962db" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f055dde1-6357-4964-9004-9e36d3494ef3" start_index="1" end="b7952ae2-e4b7-4a5d-900d-1eddef18a1c4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f055dde1-6357-4964-9004-9e36d3494ef3" start_index="2" end="ff14cc85-5c93-40cb-9746-34f5133284e0" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>