<Workspace Version="1.3.4.6666" X="126.679799651004" Y="19.0522230368823" zoom="0.691347793867188" ScaleFactor="1" Name="Group Parallel Lines" Description="Groups parallel lines or curved elements (model and detail lines) together." ID="c3cb96c8-2a86-4b70-aa5d-4627542af451" Category="GeniusLoci.Geometry">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="cf7e4098-c951-4899-b0e4-e5d705127e12" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-133.239709529186" y="239.378579990489" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Dynamo line or straight curved elements&#xD;&#xA;//(such as Model or Detail Line)&#xD;&#xA;lines" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="7c11dba4-478a-4a15-b2e4-a6f0e8b0e67c" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="559.960290470814" y="239.378579990489" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Grouped Lines" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="14f9a0c9-aec9-4af6-b051-5545b31d8ec3" type="PythonNodeModels.PythonNode" nickname="Python Script" x="335.560290470814" y="239.378579990489" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Strongly inspired by Maciek Glowka http://lubim.co

import clr
# Import RevitAPI Classes
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

# Import ToDSType extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

def isParallel(v1,v2):
  return v1.CrossProduct(v2).IsAlmostEqualTo(XYZ(0,0,0))
  
lineElements = UnwrapElement(IN[0])

directions = []
lines_groups = []
#group parallel lines together
for lineElement in lineElements:
	if hasattr(lineElement, "Explode"):
		l=lineElement.ToRevitType()
	else:
		l = lineElement.GeometryCurve
	d = l.GetEndPoint(1)-l.GetEndPoint(0)
	idx = -1
	for i in range(len(directions)):
		if isParallel(d,directions[i]):
			idx = i
			break
    
	if idx!=-1:
		lines_groups[idx].append(lineElement)
	else:
		directions.append(d)
		new_group = []
		new_group.append(lineElement)
		lines_groups.append(new_group)
      
OUT = lines_groups</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="cf7e4098-c951-4899-b0e4-e5d705127e12" start_index="0" end="14f9a0c9-aec9-4af6-b051-5545b31d8ec3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="14f9a0c9-aec9-4af6-b051-5545b31d8ec3" start_index="0" end="7c11dba4-478a-4a15-b2e4-a6f0e8b0e67c" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>