<Workspace Version="1.3.4.6666" X="26.7911505351488" Y="142.122528490386" zoom="0.426455554100617" ScaleFactor="1" Name="Lock ByReferences" Description="Add a new locked alignment through elements References.&#xD;&#xA;Paired references must be already geometrically aligned (this function will not force them to become aligned)." ID="5d199e2f-7797-410d-830a-54ac37b6e525" Category="GeniusLoci.Dimension">
  <NamespaceResolutionMap>
    <ClassMap partialName="Revit.Elements.Views.View" resolvedName="Revit.Elements.Views.View" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Revit.Application.Document.Current" resolvedName="Revit.Application.Document" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Revit.Application.Document" resolvedName="Revit.Application.Document" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="8603fd11-0140-492f-a0f3-6716ff55e4cf" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="177.713894944492" y="251.803380564428" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//View to place dimension in&#xD;&#xA;view:Revit.Elements.Views.View = Revit.Application.Document.Current.ActiveView" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="9e7cab42-d87f-46b3-bd92-c202900bf6ac" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1176.11389494449" y="318.803380564428" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Dimension" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="7d36ad8a-3e27-43b4-b029-0392bd47c89d" type="PythonNodeModels.PythonNode" nickname="Python Script" x="951.713894944492" y="318.803380564428" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>#Alban de Chasteigner 2021
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com
#https://github.com/albandechasteigner/GeniusLociForDynamo

import clr
# Import RevitAPI Classes
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import Document
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

def tolist(obj1):
    if hasattr(obj1,"__iter__"): return obj1
    else: return [obj1]

view = tolist(UnwrapElement(IN[0]))[0]
references1 = tolist(IN[1])
references2 = tolist(IN[2])
align=[]

TransactionManager.Instance.EnsureInTransaction(doc)
for ref1, ref2 in zip(references1,references2):
	align.append(doc.Create.NewAlignment(view, ref1, ref2))
	#align.IsLocked = True
TransactionManager.Instance.TransactionTaskDone()

if isinstance(IN[1], list): OUT = align
else: OUT = align[0]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="150bdc27-d457-458f-a8f3-164207393be8" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="177.713894944492" y="344.803380564428" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Aligned Autodesk.Revit.DB.Reference&#xD;&#xA;reference1" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="4de5fef8-5b13-4891-bfe4-b673bea6c367" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="177.713894944492" y="437.803380564428" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Aligned Autodesk.Revit.DB.Reference&#xD;&#xA;reference2" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="8603fd11-0140-492f-a0f3-6716ff55e4cf" start_index="0" end="7d36ad8a-3e27-43b4-b029-0392bd47c89d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7d36ad8a-3e27-43b4-b029-0392bd47c89d" start_index="0" end="9e7cab42-d87f-46b3-bd92-c202900bf6ac" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="150bdc27-d457-458f-a8f3-164207393be8" start_index="0" end="7d36ad8a-3e27-43b4-b029-0392bd47c89d" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4de5fef8-5b13-4891-bfe4-b673bea6c367" start_index="0" end="7d36ad8a-3e27-43b4-b029-0392bd47c89d" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>