<Workspace Version="1.3.4.6666" X="116.298" Y="82.341" zoom="0.8425" ScaleFactor="1" Name="Material Set Tint Color" Description="Works only in Revit 2018.1 and later.&#xD;&#xA;Enable the Tint Color Property and set the Tint Color in the Appearance Asset Element of the given material." ID="6bd8e8dc-1f82-4430-bd97-538b8cb627de" Category="GeniusLoci.Material">
  <NamespaceResolutionMap>
    <ClassMap partialName="DSCore.Color" resolvedName="DSCore.Color" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="ad18be3b-21df-4876-9569-120b0a6663c6" type="PythonNodeModels.PythonNode" nickname="Enable Tint Color and add colors" x="503.200000000001" y="275.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Inspired by Boris Shafiro from Autodesk
#Alban de Chasteigner 2018
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

def toList(obj):
    if hasattr(obj, '__iter__'): return obj
    else: return [obj]
    
mats = toList(UnwrapElement(IN[0]))
colors = toList(IN[1])

def ToRevitColor(dynamoColor):
	return Color(dynamoColor.Red, dynamoColor.Green, dynamoColor.Blue)

for mat, color in zip(mats, colors):
	appearanceAssetId = mat.AppearanceAssetId
	assetElem = doc.GetElement(appearanceAssetId)
	TransactionManager.Instance.EnsureInTransaction(doc)
	with Visual.AppearanceAssetEditScope(assetElem.Document) as editScope:
		editableAsset = editScope.Start(assetElem.Id)
		tintToggleProp = editableAsset["common_Tint_toggle"]
		tintColorProp = editableAsset["common_Tint_color"]
		tintToggleProp.Value = True
		tintColorProp.SetValueAsColor(ToRevitColor(color))
		editScope.Commit(True)
	TransactionManager.Instance.TransactionTaskDone()
	
OUT = mats</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="9621fe03-c958-4e34-babd-05e4f4283d67" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="357.2" y="269.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="material" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="c26c7977-2388-4945-9259-36d2882a8ecc" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="766.819268346913" y="270.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Material" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="f80cec7d-9e1b-4d00-8714-b293c1a8f8fb" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="24.8704254436669" y="352.199793499652" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Dynamo Color&#xD;&#xA;color:var[]..[]= DSCore.Color.ByARGB(0,0,0,0)" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="ad18be3b-21df-4876-9569-120b0a6663c6" start_index="0" end="c26c7977-2388-4945-9259-36d2882a8ecc" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9621fe03-c958-4e34-babd-05e4f4283d67" start_index="0" end="ad18be3b-21df-4876-9569-120b0a6663c6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f80cec7d-9e1b-4d00-8714-b293c1a8f8fb" start_index="0" end="ad18be3b-21df-4876-9569-120b0a6663c6" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>