<Workspace Version="1.3.4.6666" X="8.29228174480258" Y="60.7909607920359" zoom="0.784369328044827" ScaleFactor="1" Name="Material Find Texture Path" Description="Works only in Revit 2018.1 and later.&#xD;&#xA;Find the texture paths of the materials (if any)." ID="f0ed32e5-3563-4f6a-8a04-58e30538858e" Category="GeniusLoci.Material">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="6662e824-0c54-473d-9175-6e0bd5fcb2a3" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="297.439887244443" y="305.161590731918" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="material:var" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="2f292eac-e88f-48b1-a9b3-0e5f1afeea56" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="718.239887244443" y="305.161590731918" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="FilePath" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="d3db4a8a-1d27-497b-9db0-ef6bf0131a1b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="493.439887244443" y="305.161590731918" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Alban de Chasteigner 2020
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com

import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

mat = UnwrapElement(IN[0])
paths,propertyName,library=[],[],[]

assetElem = doc.GetElement(mat.AppearanceAssetId)
if assetElem:
	with Visual.AppearanceAssetEditScope(doc) as editScope:
		asset = editScope.Start(assetElem.Id)
		for idx in range(0, asset.Size):
		#idx=0
		#while idx &lt; asset.Size:
			property=asset.Get(idx)
			#if property.NumberOfConnectedProperties &lt; 1 :
			connectedAsset=property.GetSingleConnectedAsset()
			if connectedAsset:
				if connectedAsset.Name == "UnifiedBitmapSchema":
					#path.append(connectedAsset["unifiedbitmap_Bitmap"].Value)
					#path.append(connectedAsset.FindByName("unifiedbitmap_Bitmap").Value)
					paths.append(connectedAsset.FindByName("unifiedbitmap_Bitmap").Value)
				elif connectedAsset.Name == "BumpMapSchema":	
					paths.append(connectedAsset.FindByName("bumpmap_Bitmap").Value)
				path=filter(None,paths)
					#propertyName.append(property.Name) 
					#library.append(connectedAsset.LibraryName)
			#idx += 1

OUT= path if len(path)&gt;1 else path[0]</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="6662e824-0c54-473d-9175-6e0bd5fcb2a3" start_index="0" end="d3db4a8a-1d27-497b-9db0-ef6bf0131a1b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d3db4a8a-1d27-497b-9db0-ef6bf0131a1b" start_index="0" end="2f292eac-e88f-48b1-a9b3-0e5f1afeea56" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>