<Workspace Version="1.3.4.6666" X="-58.1796838098136" Y="68.9860301327192" zoom="0.803321593462598" ScaleFactor="1" Name="Railing SetPath" Description="Modify the path of an existing railing." ID="83cff94e-9d37-4d7c-88b0-ce9cac92b666" Category="GeniusLoci.Element">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="70d05ca0-3557-428c-96dd-bbb6f04084fe" type="PythonNodeModels.PythonNode" nickname="Python Script" x="590.4" y="299.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Alban de Chasteigner 2018
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

railing = UnwrapElement(IN[0])
curves = UnwrapElement(IN[1]) if isinstance(IN[1],list) else [UnwrapElement(IN[1])]

TransactionManager.Instance.EnsureInTransaction(doc)
revitCurves=[]
for curve in curves:
	revitCurves.append(curve.ToRevitType())

curveloop = CurveLoop.Create(revitCurves)
rpath = railing.SetPath(curveloop)
TransactionManager.Instance.TransactionTaskDone()

OUT = railing</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c9816fd5-4b77-4515-9da5-9c5ebdcf28bf" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="372.8" y="276" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Railing" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="b499c33a-a61e-4b37-8d18-e565e933ffec" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="372.8" y="368" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Dynamo curve&#xD;&#xA;curve" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="0e4e1fca-06ae-4f37-95ef-fc52307c96c6" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="806.4" y="306.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Railing" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="70d05ca0-3557-428c-96dd-bbb6f04084fe" start_index="0" end="0e4e1fca-06ae-4f37-95ef-fc52307c96c6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c9816fd5-4b77-4515-9da5-9c5ebdcf28bf" start_index="0" end="70d05ca0-3557-428c-96dd-bbb6f04084fe" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b499c33a-a61e-4b37-8d18-e565e933ffec" start_index="0" end="70d05ca0-3557-428c-96dd-bbb6f04084fe" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>