<Workspace Version="1.3.4.6666" X="179.2" Y="-24.8" zoom="1" ScaleFactor="1" Name="RevisionCloud to Sheet" Description="Returns the ViewSheets where this RevisionCloud appears." ID="aadb7ca2-fe47-4f1d-9306-a2c3c50c0579" Category="GeniusLoci.Sheet">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="9ed01981-aee5-4a47-ba98-258915a2a326" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="290.4" y="444" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Sheet" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="e341dce3-5edb-44e5-8269-24a2eaf4e472" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-44.8" y="442.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="revisionCloud" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="c7d844dc-42e7-4e2f-a0d9-1a8985122453" type="PythonNodeModels.PythonNode" nickname="Python Script" x="144.8" y="444" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
# Import RevitAPI Classes
clr.AddReference('RevitAPI')
import Autodesk

import System
# Load System.Core assembly that contains HashSet
clr.AddReference("System.Core")
from System.Collections.Generic import HashSet

def flatten_list(a, result=None):
	if result is None:
		result = []
	for x in a:
		for y in x:
			if isinstance(y, list):
				flatten_list(y, result)
			else:
				result.append(y)
	return result

revisions = UnwrapElement(IN[0]) if isinstance(IN[0],list) else [UnwrapElement(IN[0])]

iSet=[]
for elem in revisions:
	iSet.append(elem.GetSheetIds())
	sheets=[]
	for iSe in flatten_list(iSet):
		hashSet = HashSet[Autodesk.Revit.DB.ElementId]()
		hashSet.Add(iSe)
		for id in hashSet :
			sheets.append(elem.Document.GetElement(id))

if isinstance(IN[0], list): OUT = sheets
else: OUT = sheets[0]</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="e341dce3-5edb-44e5-8269-24a2eaf4e472" start_index="0" end="c7d844dc-42e7-4e2f-a0d9-1a8985122453" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c7d844dc-42e7-4e2f-a0d9-1a8985122453" start_index="0" end="9ed01981-aee5-4a47-ba98-258915a2a326" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
</Workspace>