<Workspace Version="1.3.4.6666" X="277.916941519659" Y="-8.7618971358383" zoom="0.784369328044827" ScaleFactor="1" Name="Rotate Fitting" Description="Rotates a fitting, at specified degree, around the axis of the primary MEP system element (pipe, duct, cable tray, conduit...).&#xD;&#xA;By MEPover on forum.dynamobim.com" ID="6740d91f-3bd7-43ac-b8b6-f8122895d26c" Category="GeniusLoci.MEP">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="c9358ebc-e908-41f4-95d6-3519cb296f1f" type="PythonNodeModels.PythonNode" nickname="Python Script" x="301.607319208332" y="206.877448071217" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>#By T_Pover
import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

import math

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

inn = [UnwrapElement(IN[0]),UnwrapElement(IN[1])]
conns = [0,1]

def disconnect(curve):
	connectors = curve.ConnectorManager.Connectors
	for conn in connectors:
		if conn.IsConnected:
			for c in conn.AllRefs:
				if conn.IsConnectedTo(c):
					conns[0] = conn
					conns[1] = c
					conn.DisconnectFrom(c)

angle = (IN[2]*math.pi)/180

TransactionManager.Instance.EnsureInTransaction(doc)
connectors = inn[0].MEPModel.ConnectorManager.Connectors
for c in connectors:
	if c.GetMEPConnectorInfo().IsPrimary:
		primary = c
		break
	primary = c
	
loc = inn[0].Location
ductloc = inn[1].Location
center = primary.CoordinateSystem.BasisZ
centerrot = XYZ(center.X,center.Y,center.Z)
line = Autodesk.Revit.DB.Line.CreateUnbound(primary.Origin,center)
disconnect(inn[1])
ductloc.Rotate(line,angle)
loc.Rotate(line,angle)
conns[0].ConnectTo(conns[1])
TransactionManager.Instance.TransactionTaskDone()

OUT =  IN[0]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="be6f7780-3daf-4538-87f6-365591ca6b8b" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="526.407319208332" y="206.877448071217" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Fitting" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="fceb1212-5013-450d-b47f-4bc474569809" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-215.992680791668" y="140.877448071217" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Fitting" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="fec73d1f-795a-49a7-837d-1f1922dc6cc6" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-215.992680791668" y="223.877448071217" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Duct, pipe or conduit attached to the fitting&#xD;&#xA;//(not connected to the primary connector)&#xD;&#xA;ConnectedElement" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="d774828f-a0a8-44e0-8676-93e0851271d0" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-215.992680791668" y="333.877448071217" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Degrees&#xD;&#xA;Angle:double[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="c9358ebc-e908-41f4-95d6-3519cb296f1f" start_index="0" end="be6f7780-3daf-4538-87f6-365591ca6b8b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fceb1212-5013-450d-b47f-4bc474569809" start_index="0" end="c9358ebc-e908-41f4-95d6-3519cb296f1f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fec73d1f-795a-49a7-837d-1f1922dc6cc6" start_index="0" end="c9358ebc-e908-41f4-95d6-3519cb296f1f" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d774828f-a0a8-44e0-8676-93e0851271d0" start_index="0" end="c9358ebc-e908-41f4-95d6-3519cb296f1f" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>