<Workspace Version="1.3.4.6666" X="-63.0666915246575" Y="74.5587240265108" zoom="0.784369328044827" ScaleFactor="1" Name="SelectByFilterAndView" Description="Retrieves elements by the name of the selection set or rule-based filter in the given view." ID="10aa4541-c3c4-4c0f-97a0-13971e52894e" Category="GeniusLoci.Select">
  <NamespaceResolutionMap>
    <ClassMap partialName="Revit.Application.Document.Current" resolvedName="Revit.Application.Document" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Revit.Application.Document" resolvedName="Revit.Application.Document" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="108d6460-2244-4869-83f3-465b43f28b26" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="812.275865897581" y="322" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Element" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="5c9f029f-0709-4e1a-a33c-66f2644d04e2" type="PythonNodeModels.PythonNode" nickname="Python Script" x="630.8" y="322.013787743386" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>##Alban de Chasteigner 2021
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com
#https://github.com/albandechasteigner/GeniusLociForDynamo

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import FilteredElementCollector, ParameterFilterElement, SelectionFilterElement
clr.AddReference('RevitServices')
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
name = IN[0]
view = UnwrapElement(IN[1])

elements, user_selection = [], []
# Get all ParameterFilterElements in doc
filter_elements = FilteredElementCollector(doc).OfClass(ParameterFilterElement)
filter_names = [f.Name for f in filter_elements]
filters = [f.GetElementFilter() for f in filter_elements]
filter_dict = dict(zip(filter_names, filters))

if name in filter_dict:
	filter = filter_dict[name]
	elements = FilteredElementCollector(doc,view.Id).WhereElementIsNotElementType().WherePasses(filter).ToElements()

selection_sets = FilteredElementCollector(doc,view.Id).OfClass(SelectionFilterElement)

for s in selection_sets:
	if s.Name == name:
		ids = s.GetElementIds()
		elements = [doc.GetElement(e) for e in ids]
		
OUT = elements</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="e8bf3034-a68e-4a76-b4c3-100442876928" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="374" y="323.613787743386" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="FilterName : string" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="57984652-499d-48f7-a74e-477dd535fea7" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="58.7977437300632" y="398.490606279549" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="view : var= Revit.Application.Document.Current.ActiveView" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="5c9f029f-0709-4e1a-a33c-66f2644d04e2" start_index="0" end="108d6460-2244-4869-83f3-465b43f28b26" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e8bf3034-a68e-4a76-b4c3-100442876928" start_index="0" end="5c9f029f-0709-4e1a-a33c-66f2644d04e2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="57984652-499d-48f7-a74e-477dd535fea7" start_index="0" end="5c9f029f-0709-4e1a-a33c-66f2644d04e2" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>