<Workspace Version="1.3.4.6666" X="227.00292181875" Y="167.3679380625" zoom="0.593767140625" ScaleFactor="1" Name="SelectByView" Description="Collects elements visible in the View of the active or given document." ID="ca981a1a-bf70-4374-a2cd-428fb7758095" Category="GeniusLoci.Select">
  <NamespaceResolutionMap>
    <ClassMap partialName="Revit.Application.Document.Current" resolvedName="Revit.Application.Document" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Revit.Application.Document" resolvedName="Revit.Application.Document" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="fcc8e2df-7ad6-4b32-b665-0e4c498e19ca" type="PythonNodeModels.PythonNode" nickname="Python Script" x="311.2" y="280.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Alban de Chasteigner 2021
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com
#https://github.com/albandechasteigner/GeniusLociForDynamo

import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import FilteredElementCollector, Document, Category

def tolist(x):
    if hasattr(x,'__iter__'): return x
    else : return [x]

views = tolist(UnwrapElement(IN[0]))
elements = []

for view in views:
	doc=view.Document
	#Filter ExtentElem
	collector = FilteredElementCollector(doc, view.Id).ToElements().FindAll(lambda x :  x.Category != None)
	elements.append(collector)

if len(elements)&gt;1 : OUT = elements
else: OUT = elements[0]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="0bf15e61-46d7-41ec-946e-76f449775dc4" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-280.4" y="278.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//View of current or given document&#xD;&#xA;view:var[]..[] = Revit.Application.Document.Current.ActiveView" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="dc7d4243-efa7-4846-bad7-53a7f59f5eb0" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="480.88610143765" y="281.030265014903" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="fcc8e2df-7ad6-4b32-b665-0e4c498e19ca" start_index="0" end="dc7d4243-efa7-4846-bad7-53a7f59f5eb0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0bf15e61-46d7-41ec-946e-76f449775dc4" start_index="0" end="fcc8e2df-7ad6-4b32-b665-0e4c498e19ca" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>