<Workspace Version="1.3.4.6666" X="117.98980746946" Y="108.130409727904" zoom="0.541716480397306" ScaleFactor="1" Name="SelectByCategoryInHostView" Description="Collects the elements of the given document by category and host view (3D view or Plan View).&#xD;&#xA;The transform CS is returned only with a LinkInstance input." ID="45627d39-aee2-479b-8d50-29c7e20c4c35" Category="GeniusLoci.Select">
  <NamespaceResolutionMap>
    <ClassMap partialName="Revit.Elements.Views.View3D" resolvedName="Revit.Elements.Views.View3D" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Revit.Application.Document.Current" resolvedName="Revit.Application.Document" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Revit.Application.Document" resolvedName="Revit.Application.Document" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="21e0513d-21c2-497a-8d31-8f7072034275" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-205.212209779996" y="203.955405184073" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//View Plan or ThreeDView of the active document&#xD;&#xA;view: var[]..[] = Revit.Application.Document.Current.ActiveView" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="baaf42c0-c9a1-4592-89cd-18ea5c4fa65d" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="239.681985596318" y="293.071550114653" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="category" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="473a671d-61ed-4250-977d-c9165397ddf1" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-63.3244329984166" y="371.893503494916" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// Use only if you want to query a linked model&#xD;&#xA;docOrRevitLinkInstance : var[] = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="cd8c4e7c-bb21-4048-b526-5df7c11b9ffe" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="613.679727807558" y="244.580068048111" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];&#xA;x[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="aa97dc3a-3425-4dbc-ac48-4c1b11387ec1" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="750.628578431806" y="231.98315072029" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="942d47bf-09ae-480a-be5f-38526384f021" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="749.505920838221" y="297.097291148235" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Transform" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="46b4fa76-c07f-45bc-bf14-509d40395001" type="PythonNodeModels.PythonNode" nickname="ByCategoryInHostView" x="424.365167779055" y="242.927468357507" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>#Alban de Chasteigner 2018
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com
#Code snippet for plan view by Cyril Poupin on Dynamo Forum

import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference('System')
from System.Collections.Generic import List

def tolist(x):
    if hasattr(x,'__iter__'): return x
    else : return [x]

views = tolist(UnwrapElement(IN[0]))
cats = tolist(UnwrapElement(IN[1]))
inputdocs = tolist(UnwrapElement(IN[2]))
transforms,transf = [], []

for inputdoc in inputdocs :
	if inputdoc == None:
		doclnk = DocumentManager.Instance.CurrentDBDocument
	elif isinstance(inputdoc,Document):
		doclnk = inputdoc
	elif isinstance(inputdoc,RevitLinkInstance):
		doclnk = inputdoc.GetLinkDocument()
		try:
			transf = inputdoc.GetTotalTransform()
			transforms.append(transf.ToCoordinateSystem(1))
		except: 
			transforms.append(None)
	else: doclnk = DocumentManager.Instance.CurrentDBDocument

for view in views:
	if view.ViewType == ViewType.ThreeD:
		sectionbox = view.GetSectionBox()
		transform = sectionbox.Transform
		sboxoriginx = transform.Origin.X
		sboxoriginy = transform.Origin.Y
		sboxoriginz = transform.Origin.Z
		minx = sectionbox.Min.X + sboxoriginx
		maxx = sectionbox.Max.X + sboxoriginx
		miny = sectionbox.Min.Y + sboxoriginy
		maxy = sectionbox.Max.Y + sboxoriginy
		minz = sectionbox.Min.Z + sboxoriginz
		maxz = sectionbox.Max.Z + sboxoriginz
		outLine = Outline(XYZ(minx, miny, minz), XYZ(maxx, maxy, maxz))
		
	elif view.ViewType == ViewType.CeilingPlan or view.ViewType == ViewType.EngineeringPlan or view.ViewType == ViewType.FloorPlan :
		bbxView = view.CropBox
		if transf :
			bbxView.Transform = transf
		viewRange = view.GetViewRange() 
		topLevel = doc.GetElement(viewRange.GetLevelId(PlanViewPlane.TopClipPlane))
		topOffset = viewRange.GetOffset(PlanViewPlane.TopClipPlane)
	
		bttmLevel = doc.GetElement(viewRange.GetLevelId(PlanViewPlane.BottomClipPlane))
		bttmOffset = viewRange.GetOffset(PlanViewPlane.BottomClipPlane)

		cutLevel = doc.GetElement(viewRange.GetLevelId(PlanViewPlane.CutPlane))
		cutOffset = viewRange.GetOffset(PlanViewPlane.CutPlane)
		
		if bttmLevel : bbxView.Min = XYZ(bbxView.Min.X, bbxView.Min.Y, bttmLevel.Elevation + bttmOffset)
		else:  bbxView.Min = XYZ(bbxView.Min.X, bbxView.Min.Y, cutLevel.Elevation + bttmOffset)
		if topLevel :  bbxView.Max = XYZ(bbxView.Max.X, bbxView.Max.Y, topLevel.Elevation + topOffset)
		else: bbxView.Max = XYZ(bbxView.Max.X, bbxView.Max.Y, cutLevel.Elevation + cutOffset)
		
		outLine = Outline(bbxView.Min, bbxView.Max) 		
		
catlist = [cat.Id for cat in cats]
filtercats = List[ElementId](catlist)
catfilter = ElementMulticategoryFilter(filtercats)
	
filterBbxInside = BoundingBoxIsInsideFilter(outLine)
filterBbxInters = BoundingBoxIntersectsFilter(outLine)
filterBbx = LogicalOrFilter(filterBbxInside, filterBbxInters)
andfilter = LogicalAndFilter(catfilter,filterBbx)

collector = FilteredElementCollector(doclnk).WherePasses(andfilter).ToElements()

OUT = collector, transforms</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="21e0513d-21c2-497a-8d31-8f7072034275" start_index="0" end="46b4fa76-c07f-45bc-bf14-509d40395001" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="baaf42c0-c9a1-4592-89cd-18ea5c4fa65d" start_index="0" end="46b4fa76-c07f-45bc-bf14-509d40395001" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="473a671d-61ed-4250-977d-c9165397ddf1" start_index="0" end="46b4fa76-c07f-45bc-bf14-509d40395001" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cd8c4e7c-bb21-4048-b526-5df7c11b9ffe" start_index="0" end="aa97dc3a-3425-4dbc-ac48-4c1b11387ec1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cd8c4e7c-bb21-4048-b526-5df7c11b9ffe" start_index="1" end="942d47bf-09ae-480a-be5f-38526384f021" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="46b4fa76-c07f-45bc-bf14-509d40395001" start_index="0" end="cd8c4e7c-bb21-4048-b526-5df7c11b9ffe" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>