<Workspace Version="1.3.4.6666" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Wall's Elevation Profile" Description="Obtains the curves which bound the wall's elevation profile.&#xD;&#xA;Only works with a wall whose profile has been edited." ID="17368c49-5ab9-46a9-a399-efdfa7f1d1d5" Category="GeniusLoci.CompoundStructure">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="f7bfc21a-458b-4fc1-945a-016f16c0d157" type="PythonNodeModels.PythonNode" nickname="Python Script" x="322.8" y="237.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Alban de Chasteigner 2019
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com

import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)
from Revit.Elements import *

clr.AddReference('RevitAPIIFC')
from Autodesk.Revit.DB.IFC import *

walls = UnwrapElement(IN[0]) if isinstance(IN[0],list) else [UnwrapElement(IN[0])]

curvess=[]
for wall in walls :
	if ExporterIFCUtils.HasElevationProfile(wall):
		profile = ExporterIFCUtils.GetElevationProfile(wall)
		for curve in profile:
			curves=[]
			for curv in curve:
				curves.append(curv.ToProtoType())
			curvess.append(curves)
	else:
		pass
		
OUT = curvess</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="f3692376-cc5e-46fb-a465-125e5d529d5d" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="219.2" y="233.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="wall" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="ea2c2ca5-de1d-459a-9f2b-a4257aa098cc" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="489.6" y="239.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Curves" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="f7bfc21a-458b-4fc1-945a-016f16c0d157" start_index="0" end="ea2c2ca5-de1d-459a-9f2b-a4257aa098cc" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f3692376-cc5e-46fb-a465-125e5d529d5d" start_index="0" end="f7bfc21a-458b-4fc1-945a-016f16c0d157" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>